(* 
  The sequence of triangle numbers is generated by adding the natural numbers.
  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
  ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred divisors?
 *)

open Core_kernel

let count_factors n =
  if n <= 2 then invalid_arg "n must be > 2" else
  let rec count_factors' accum i =
    if i * i > n then
      accum
    else if n % i = 0 then
      count_factors' (accum + 2) (i + 1)
    else
      count_factors' accum (i + 1)
  in
  count_factors' 2 2

let solve () =
  let rec solve' triangular i =
    let nfactors = count_factors triangular in
    if nfactors > 500 then triangular
    else solve' (triangular + i + 1) (i + 1)
  in
  solve' 6 3
  |> string_of_int
