(*
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.
 *)

open Core_kernel

let solve () =
  let max_fib = 4000000 in
  let rec loop last cur acc =
    if cur > max_fib then acc else
    if cur mod 2 = 0
    then loop cur (last + cur) (acc + cur)
    else loop cur (last + cur) acc
  in
  loop 1 2 0 |> string_of_int
  (* 4613732 *)
